[project]
name = "french-b2-simplifier"
version = "0.1.0"
description = "Enforce B2 vocabulary compliance by simplifying French text to B2 level with strict word list checking"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "mcp[cli]>=1.2.0",
    "spacy>=3.7.0",
]
